name: airbnb_project
channels:
  - defaults

dependencies:
  - pandas=0.25.3
  - numpy=1.17.4
  - pip=19.3.1
  - python=3.7.3
  - numba=0.48.0
  - python-graphviz=0.8


  - pip:
    - xgboost==1.0.1
    - scikit-learn==0.21.3
    - pre-commit==1.18.3
    - matplotlib==3.1.1
    - nbsphinx==0.4.2
    - sphinx==2.2.0
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==1.0.0