#! python
dates = [
    "2018_04_21",
    "2018_07_31",
    "2018_08_27",
    "2018_09_21",
    "2018_10_18",
    "2018_11_21",
    "2018_12_21",
    "2019_01_29",
    "2019_02_18",
    "2019_03_28",
    "2019_04_27",
    "2019_05_29",
    "2019_06_29",
    "2019_07_28",
    "2019_08_31",
    "2019_09_30",
    "2019_10_30",
    "2019_11_29"
    ]


deps_keys = [("OUT_PREDICTION", f"{date}_prediction.csv") for date in dates]
deps_keys.append(("IN_DATA", 'TurkStat_data/monthly_change_ist.csv'))
deps_keys.append(("IN_DATA", 'TurkStat_data/yearly_change_ist.csv'))

def build(ctx):

        ctx(
            features="run_py_script",
            source="figure_maker.py",
            deps=[ctx.path_to(ctx, key[0], key[1]) for key in deps_keys],
            target=[
            	ctx.path_to(ctx, "OUT_FIGURES", "monthly_change_figure.png"),
            	ctx.path_to(ctx, "OUT_FIGURES", "yearly_change_figure.png")
            ],
            append=dates,
            name="figure_maker",
            )
